### ISSUE TITLE
Layers for basins

### ISSUE THREAD

**Issue by pollardld** [Ecotrust/ucsrb#113]
**ppt basin layers loaded into app.**

### Tasks

- [x] create layer for overlapping basins with below attributes
- [x] create layer for discrete (non-overlapping) basins with below attrs

- [x] import overlapping basins
- [x] import discrete basins

### Attributes
'ppt_ID'
'area'
'mean_elev'
'avg_slp'
'slp_gt60'
'elev_dif'
'mean_shade'
'veg_prop'
'thc_11'
'thc_12'
'thc_13'
'thc_14'
'thc_15'
'thc_21'
'thc_22'
'thc_23'
'thc_24'
'thc_25'
'fc_11'
'fc_12'
'fc_13'
'fc_14'
'fc_15'
'fc_21'
'fc_22'
'fc_23'
'fc_24'
'fc_25'
'dwnst_ppt'
