### ISSUE TITLE
Updated huc10, huc12, rma, veg units

### ISSUE THREAD

**Issue by pollardld** [Ecotrust/ucsrb#121]
Get layers loaded into app

### ToDos

- [x] huc10s with project boundary constraints
- [x] huc12s with project boundary constraints
- [x] RMAs { id, name, geometry }
-_-_-
- [x] Updated veg units<sup>*</sup>

<sup>*</sup> *save for last*

***  

- [ ] Allow for loading additional scenarios (USFS may want to load data)

**Comment by jtutak** [comment]
In \\Neoterra\gis\projects\UCSRB_2016\data\Processed\ForFilteringComponent
- HUC10_WCol.shp
- HUC12_WCol.shp
- LandMgmtPlan_OKAWEN_WCol.shp

**Comment by jtutak** [comment]
HUC10s (watersheds) and HUC12s (subwatersheds) styled.

**Comment by jtutak** [comment]
Management units are styled
